name: MoreMaterials
version: 1.6.2
description: Custom blocks and items!
authors: [ZNickq, IceReaper]
website: http://www.spoutmaterials.net

depend: [Spout]
main: net.morematerials.morematerials.Main

commands:
  sm:
    description: Some basic commands!
    usage: /<command> [?]
  smgive:
    description: Gives you a custom material.
    usage: /<command> [custom material] {amount}
    permission: spoutmaterials.give
  smadmin:
    description: Internal helper functions.
    usage: |
      /<command> [list] - List all currently installed smp files.
      /<command> [updates] - List all updatable smp files.
      /<command> [install] [smpPackage] {version} - Install specified smp file in specified version (Defaults to latest).
      /<command> [uninstall] [smpPackage] - Uninstall specified smp file.
    permission: spoutmaterials.admin

permissions:
  spoutmaterials.*:
    description: Allows access to all of SpoutMaterials' functionality.
    default: op
    children:
      spoutmaterials.admin: true
      spoutmaterials.craft.*: true
  spoutmaterials.admin:
    description: Access to smp commands.
    default: op
    children:
      spoutmaterials.give: true
  spoutmaterials.give:
    description: Allows spawning SpoutMaterials blocks and items.
    default: op
  spoutmaterials.craft:
    description: Allows crafting of SpoutMaterials blocks and items.
    default: true
    children:
      spoutmaterials.craft.material: true
