name: MoreMaterials
version: 1.8
description: Custom blocks and items!
authors: [ZNickq, IceReaper]
website: http://www.morematerials.net

depend: [Spout, Furnace Api]
main: net.morematerials.MoreMaterials

commands:
  mm:
    description: Some basic commands!
    usage: /<command> [?]
  mmdebug:
    description: Show information about current material.
    usage: /<command>
  mmgive:
    description: Gives you a custom material.
    usage: /<command> [custom material] {amount}
    permission: morematerials.give

permissions:
  morematerials.*:
    description: Allows access to all of MoreMaterials' functionality.
    default: op
    children:
      morematerials.admin: true
      morematerials.craft: true
  morematerials.admin:
    description: Access to commands.
    default: op
  morematerials.craft:
    description: Allows crafting of MoreMaterials blocks and items.
    default: true
