name: SpoutMaterials
version: 1.6
author: ZNickq, IceReaper
depend: [Spout]
description: Custom blocks and items!
main: net.spoutmaterials.spoutmaterials.Main
commands:
  smgive:
    description: Gives you a custom object.
    usage: /<command> [custom blockname] {number of blocks}
  smdebug:
    description: Internal helper functions.
    usage: /<command> [ask dev ^^]
  smupdate:
    description: Update functions
    usage: /<command> [packageName]
  sm:
    description: General plugin informations.
    usage: /sm
permissions:
  spoutmaterials.*:
    description: Allows access to all of SpoutMaterials' functionality.
    default: op
  spoutmaterials.debug:
    description: Experimental features, for fast debugging.
    default: op
  spoutmaterials.give:
    description: Allows spawning SpoutMaterials blocks and items.
    default: op
    children:
      spoutmaterials.give.package.name: true
      spoutmaterials.give.name: true
  spoutmaterials.craft:
    description: Allows crafting of SpoutMaterials blocks and items.
    default: op
    children:
      spoutmaterials.give.package.name: true
      spoutmaterials.give.name: true