name: SpoutMaterials
version: 1.6
author: ZNickq, IceReaper
depend: [Spout]
description: Custom blocks and items!
main: net.spoutmaterials.spoutmaterials.SpoutMaterials
commands:
  smgive:
    description: Gives you a custom object.
    usage: /<command> [custom blockname] {number of blocks}
  smdebug:
    description: Internal helper functions.
    usage: /<command> [ask dev ^^]
  sm:
    description: General plugin informations.
    usage: /sm
permissions:
  spoutmaterials.*:
    description: Allows access to all of SpoutMaterials' functionality.
    default: op
    children:
      spoutmaterials.debug: true
      spoutmaterials.give: true
  spoutmaterials.debug:
    description: Experimental features, for fast debugging.
    default: op
  spoutmaterials.give:
    description: Allows access to all of SpoutMaterials' give commands.
    default: op
